### ISSUE TITLE
Unable to open files in VS

### ISSUE THREAD

**Issue by jd-ln** [ArturoDent/custom-comments#9] opened 2024-06-11 16:10 UTC
First file opened is okay, every subsequent file causes this error. Since the extension auto updated today.

If I close VS and reopen, I can open one file, but same issue afterwards. One other member of my team had the same issue and we narrowed it down to this extension.

`Unable to open 'file.jl'`
`Cannot read properties of undefined (reading 'charAt')`

**Comment by ArturoDent** [comment] 2024-06-11 18:14
What is the `"custom-language-properties": {}` setting you are using?

What extension are you using that provides language support for `jl` files (which I assume is the language you are using this extension to modify)?

**Comment by Jack-Diamond-1** [comment] 2024-06-11 18:22
<img width="373" alt="image" src="https://github.com/ArturoDent/custom-language-properties/assets/99433795/18f27ca4-dac3-4b97-8551-e58775851fbe">

And this is the julia extension: https://github.com/julia-vscode/julia-vscode

**Comment by ArturoDent** [comment] 2024-06-11 18:23
Did you do an extension Bisect to determine it was this extension causing problems?

**Comment by Jack-Diamond-1** [comment] 2024-06-11 18:24
Disabled all extensions besides this and it fixes the problem. If I re-enable this, the behaviour starts again instantly. Commenting out my settings doesn't fix it either

**Comment by ArturoDent** [comment] 2024-06-11 18:42
I assume you are on v0.6.6.  The odd thing is the extension doesn't use `charAt`...

I would ask that you do run the command `Help: Start Extension Bisect` and see what that tool reveals.  It goes pretty fast.  Thanks.

[ Okay, I installed the Julia extension and can reproduce the error so that helps. ]

**Comment by ArturoDent** [comment] 2024-06-11 19:26
Please try v0.6.7, just uploaded, might take a couple of minutes to appear.  

Appears to be related to an earlier attempt I made to support `autoClosingPairs` - only to discover that vscode's implementation of extension access to that property is quite flawed.

I did a better job of removing any lingering related code and now I can't reproduce the error in the Extension Host anymore.

![customLanguageCharAtError](https://github.com/ArturoDent/custom-language-properties/assets/31813701/06eb8453-a4ee-4613-aa0e-698b122e6324)

**Comment by Jack-Diamond-1** [comment] 2024-06-12 08:06
Heu @ArturoDent - Have updated to .6.7 and it's solved the problem

**Comment by Jack-Diamond-1** [comment] 2024-06-12 08:06
Thanks for your quick work!

**Comment by ArturoDent** [comment] 2024-06-14 17:03
I'm going to close this as fixed.  Let me know if there are any other concerns.

**Closed as completed** 2024-06-14 17:04 UTC
